# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 专注成长.享受生活 # ex. I m Chuan
name: 一笑而过 # ex. DONGChuan
email: 1092138456@qq.com
location: 位置 # ex. Nice, France
company: 公司
company_url: my_company_website
github_url: https://github.com/laughitover
github_username: laughitover
description: 描述我的网站
favicon: main_favicon.ico # Image must be in assets/images
repository: github_username/github_username.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
# url: http://localhost:4000
#url: https://laughitover.github.io/
url: http://www.laughitover.com/
enforce_ssl: laughitover.com
## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /pages/open-source
    label: Open-Source

  -
    href: /pages/blog
    label: Blog

  -
    href: /pages/bookmark
    label: Bookmark

  -
    href: /pages/about
    label: About

# selected articles
classes:

  -
    href: /life.html
    name: 享受生活
    describe: 乐观豁达，品味人生

# labels. my blog key words
labels:

  -
    href: /life.html
    name: life

  -
    href: /pages/open-source.html
    name: Code

  -
    href: /others.html
    name: others


# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
#analytics :
#  provider : google
#  google :
#      tracking_id : 'tracking_id'  # ex. UA-72165600-X

# baidu analytics


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin ]




# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: ityouknow
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: ityouknow
    repo: blog-comments
    oauth:
        client_id: 61bfc53d957e74e78f8f
        client_secret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: laughitover
    repo: blog-comments
    clientID: d2b22dbdb6a88af38a9b
    clientSecret: 287f88216f9c479211c969aaeb346916eb36e764
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
